# Generated by Django 3.2.4 on 2022-09-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('clogo', models.ImageField(upload_to='static/company')),
            ],
        ),
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=30)),
                ('Msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sturegister',
            fields=[
                ('rno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=40)),
                ('smobile', models.CharField(max_length=50)),
                ('gmobile', models.CharField(max_length=50)),
                ('pic', models.ImageField(null=True, upload_to='static/profile/')),
                ('rdate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ugallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdes', models.CharField(max_length=200)),
                ('picture', models.ImageField(default='', upload_to='static/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='vgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.TextField()),
                ('vdes', models.TextField()),
                ('vtitle', models.CharField(max_length=200)),
                ('vdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='stuplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('stupic', models.ImageField(null=True, upload_to='static/profile')),
                ('designation', models.CharField(max_length=70)),
                ('syear', models.CharField(max_length=40)),
                ('cpic', models.ImageField(upload_to='static/company')),
                ('rdate', models.DateField()),
                ('pcity', models.CharField(max_length=60)),
                ('cname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company')),
            ],
        ),
    ]
