# Generated by Django 3.2.4 on 2022-09-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=30)),
                ('seats', models.CharField(max_length=50)),
                ('hod', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('cpic', models.ImageField(null=True, upload_to='static/course')),
                ('sdate', models.CharField(max_length=100)),
                ('eligibilty', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=200)),
            ],
        ),
    ]
