# Generated by Django 3.2.4 on 2022-09-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_mycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='hodpic',
            field=models.ImageField(null=True, upload_to='static/hod'),
        ),
    ]
