# Generated by Django 3.2.4 on 2022-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_infra_infras'),
    ]

    operations = [
        migrations.CreateModel(
            name='infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=30)),
                ('ipic', models.ImageField(null=True, upload_to='static/infra')),
            ],
        ),
        migrations.DeleteModel(
            name='infras',
        ),
    ]
