# Generated by Django 3.2.4 on 2022-09-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220909_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='infrastructure',
            new_name='infra',
        ),
    ]
