# Generated by Django 3.2.4 on 2022-09-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_infrastructure_infra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='infra',
            new_name='infrastructure',
        ),
    ]
