# Generated by Django 3.2.4 on 2022-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_infra_infrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('tbranch', models.CharField(max_length=50)),
                ('tpic', models.ImageField(null=True, upload_to='static/faculty')),
            ],
        ),
    ]
